// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkR68GvY2ZDtMp-VJrYvtHOI86svTE3I',
    appId: '1:614519210447:web:ef739a5fa16c56b49692ba',
    messagingSenderId: '614519210447',
    projectId: 'ehgezly-df60a',
    authDomain: 'ehgezly-df60a.firebaseapp.com',
    storageBucket: 'ehgezly-df60a.appspot.com',
    measurementId: 'G-GJXKB2G6E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdlkjyM5VGhg1vf00f0xnixs7PYZm1pAM',
    appId: '1:614519210447:android:96ba05c1582d42749692ba',
    messagingSenderId: '614519210447',
    projectId: 'ehgezly-df60a',
    storageBucket: 'ehgezly-df60a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHxaRi6LmC2matzyhE1V-vEnMhY2dp5p8',
    appId: '1:614519210447:ios:48ad0e167b64e7709692ba',
    messagingSenderId: '614519210447',
    projectId: 'ehgezly-df60a',
    storageBucket: 'ehgezly-df60a.appspot.com',
    iosBundleId: 'com.example.bookingDepiProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkR68GvY2ZDtMp-VJrYvtHOI86svTE3I',
    appId: '1:614519210447:web:2d033272fb450ca69692ba',
    messagingSenderId: '614519210447',
    projectId: 'ehgezly-df60a',
    authDomain: 'ehgezly-df60a.firebaseapp.com',
    storageBucket: 'ehgezly-df60a.appspot.com',
    measurementId: 'G-S88CKJKC0R',
  );
}
